<Project>
    <Import Project="$(SolutionDir)Build\Base.targets"
            Condition=" '$(MSBuildProjectDirectory)' != '' "/>
    <Import Project="$(SolutionDir)Build\ManageDlls.targets"
            Condition=" '$(MSBuildProjectDirectory)' != '' and !$(MSBuildProjectDirectory.Contains('\UnitTest\')) " />
</Project>