<Project>
    <Import Project="$(SolutionDir)Build\Base.props"
            Condition=" '$(MSBuildProjectDirectory)' != '' "/>
    <Import Project="$(SolutionDir)Build\ManageDlls.props"
            Condition=" '$(MSBuildProjectDirectory)' != '' and !$(MSBuildProjectDirectory.Contains('\UnitTest\')) "/>
</Project>